---
title: "Notes: Honka (2014) Quantifying Search and Switching Costs in the U.S. Auto Insurance Industry"
author: "Yuki KAYABA"
date: "1/15/2023"
site: bookdown::bookdown_site
output:
  bookdown::gitbook: default
output_dir: docs
bookdown::gitbook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
```

# Summary of the Paper

（ひとことメモ）

- 


## Motivation

- This paper focuses on two types of market frictions, namely, consumer search and switching costs
- Quantifying market frictions is important for the following reasons
  - Accounting for consumers' limited information is necessary to recover true consumer preferences
  - Both search and switching costs can increase companies' market power and lead to higher prices for consumers

## Related Literature

- 

## Contribution

- 

# Details of the Paper

## Model

### Main Model Assumptions

- The consumer’s search and purchase decisions are conditional on his choice of coverage
- Consumers search to resolve uncertainty about prices
- Consumers use a simultaneous search approach

### Model Development

**Notations**

- $i = 1, ..., N$ consumers
- $m = 1, ..., M$ markets (states)
- $j = 1, ..., J$ insurance companies
- $j = 1, ..., J_{m}$ insurance companies within state $m$
- $\Psi_{m}$: the set of available auto insurers in state $m$
- $c_{i}$: consumer search costs
- $k$: the number of searches that a consumer conducts
- $S_{i}$: the set of companies that a consumer searches
- $\overline{S_{i}}$: the set of companies that a consumer does not search
- $j_{I_{ij, t-1}}$: the previous insurer
- $C_{i} = S_{i} \cup \{ j_{I_{ij, t-1}} \}$: the consumer's consideration set
- $\Psi_{m} = C_{i} \cup \overline{S_{i}}$

**Indirect Utility**

Consumer $i$'s indirect utility for company $j$ is given by:
    
$$
u_{ij} = \alpha_{ij} + \beta_{i} I_{ij, t-1} + \gamma p_{ij} + X_{ij}\rho + W_{i} \phi + \epsilon_{ij}
$$
    
where $\beta_{i} = \tilde{\beta} + Z_{i} \kappa$.

- $\epsilon_{ij}$ captures a component of the utility that is observed by the consumer, but not the researcher
- $\epsilon_{ij}$ follows an EV Type I distribution with location parameter 0 and scale parameter 1
- $\alpha_{ij}$ are consumer-specific brand intercepts
- Let $\alpha = (\alpha_{1}, ..., \alpha_{J})$ and assume that $\alpha$ follows a MVN distribution with mean $\overline{\alpha}$ and covariance matrix $\Sigma_{\alpha}$
- $\beta_{i}$ captures consumer inertia
- $I_{ij, t-1}$ is a dummy variable indicating whether company $j$ is consumer $i$'s previous insurer
- $Z_{i}$ contains demographic factors, psychographic factors, and customer satisfaction with the previous insurer
- Inertia $\beta_{i}$ is divided into two parts (to separately evaluate its effects in counterfactuals):
  - **customer switching costs**: the constant $\tilde{\beta}$, demographic factors, and psychographic factors
  - **customer satisfaction**: customer satisfaction
- $\gamma$ captures price sensitivity
- $p_{ij}$ denotes the price charged by company $j$
- Assume prices $p_{ij}$ follows as EV Type I distribution with location parameter $\eta_{ij}$ and scale parameter $\mu$ [^1]
- $X_{ij}$ is a vector of product- and consumer-specific attributes
- $W_{i}$ contaions demographic factors, psychographic factors, and regional fixed effects that are common across $j$

[^1]: ConsumerはPriceはSearchするまでわからないがPriceの分布はわかっている。また、Consumer BeliefはRational Expectationと仮定（後述）

**EIU (Expected Indirect Utility)**

- Assume that consumers know all company characteristics except for prices (searching for prices is costly)
- Consumers do not search their previous insurer as insurance companies automatically send their customers renewal notices and thus consumers receive a free quote from their previous insurer ("fall-back option")
- Before collecting price information, consumers have to decide which companies to search
- Following Chade and Smith (2005), assume that first order stochastic dominance among the price belief distributions and use the optimal selection strategy
- The consumer makes the decisions of which and how many companies to search at the same time
- Consumer $i$'s expected indirect utility (EIU) is given by:

$$
E \left[ u_{ij} \right] = \alpha_{ij} + \beta_{i} I_{ij, t-1} + \gamma E \left[ p_{ij} \right] + X_{ij}\rho + W_{i} \phi + \epsilon_{ij}
$$

- Consumer $i$ ranks all companies other than his previous insurance provider according to their EIUs and then picks the top $k$ companies to search
- $R_{ik}$ denotes the set of top $k$ companies consumer $i$ ranks highest according to their EIU
- To decide on the number of companies $k$, the consumer calculates the net benefit of all possible search sets _given the ranking of EIUs_
- A consumer's benefit of a searched set is then given by the expected _maximum_ utility among the searched brands
- Given the EV distribution of prices, the maximum utility has also an EV distribution:

$$
\max_{j \in R_{ik}} u_{ij} \sim EV \left( \frac{1}{b} \ln \sum_{j \in R_{ik}} \exp(ba_{ij}), b \right)
$$

with $a_{ij} = \alpha_{ij} + \beta_{i} I_{ij, t-1} + \gamma \eta_{ij} + X_{ij}\rho + W_{i} \phi + \epsilon_{ij}$ and $b = \frac{\mu}{\gamma}$.

- The benefit of a searched set is given by

$$
E \left[ \max_{j \in R_{ik}} u_{ij} \right] = \tilde{a}_{R_{ik}} + \frac{e_{c}}{b}
$$

where $\tilde{a}_{R_{ik}} = \frac{1}{b} \ln \sum_{j \in R_{ik}} \exp(ba_{ij})$ and $e_{c}$ is the Euler constant

- The consumer picks $S_{ik}$ which maximizes his net benefit of searching denoted $\Gamma_{i, k+1}$, i.e. the expected utility among the considered companies minus the cost of search:

$$
\Gamma_{i, k+1} = E \left[ \max_{j \in R_{ik} \cup \left\{j_{I_{ij, t-1}} \right\}} u_{ij} \right] - kc_{i}
$$

- The consumer picks the number of searches $k$ which maximizes his net benefit of search
- The consumer then picks the company with the highest utility among the considered companies:

$$
j = \mathop{\rm argmax}\limits_{\boldsymbol{j \in C_{i}}} u_{ij}
$$


## Estimation

- Differences between what the consumer observes and what the researcher observes:
  1. Whereas the consumer knows the distributions of prices in the market, the researcher estimates the parameters defining the price distributions
  2. Whereas the consumer knows his psychographic factors and brand preferences, the researcher estimates the psychographic and observed brand preference factors
  3. Whereas the consumer knows each company’s position in the EIU ranking, the researcher only partially observes the ranking by observing which companies are being searched and which ones are not being searched
  4. In contrast to the consumer, the researcher does not observe $\alpha_{ij}$ and $\epsilon_{ij}$
  
- Tackle the first two points by integrating over the empirical distributions of the price, psychographics and observed brand preferences parameters given the sampling error associated with estimating these parameters
- To address the third issue, I point out that partially observing the ranking contains information that allows us to estimate the composition of consideration sets
- Because the consumer ranks the companies according to their EIU and only searches the highest ranked companies, the researcher knows from observing which companies are searched that the EIUs among all the searched companies have to be larger than the EIUs of the non-searched companies

$$
\min_{j \in S_{i}} E \left[ u_{ij} \right] \geq \max_{j' \notin S_{i}} E \left[ u_{ij'} \right] 
$$

- As a consumer decides simultaneously which and how many companies to search, the following condition has to hold for any searched set:

$$
\min_{j \in S_{i}} E \left[ u_{ij} \right] \geq \max_{j' \notin S_{i}} E \left[ u_{ij'} \right] \cap \Gamma_{i, k} \geq \Gamma_{i, k'} \quad \forall k \neq k'
$$

- Then the probability that a consumer picks a consideration set $\Upsilon$ is given by

$$
P_{i \Upsilon \mid \alpha, \epsilon} = \Pr \left( \min_{j \in S_{i}} E \left[ u_{ij} \right] \geq \max_{j' \notin S_{i}} E \left[ u_{ij'} \right] \cap \Gamma_{i, k + 1} \geq \Gamma_{i, k' + 1} \quad \forall k \neq k' \right)
$$
- Next, the consumer's choice probability conditional on his consideration set is

$$
P_{ij \mid \Upsilon \alpha \epsilon} = \Pr (u_{ij} \geq u_{ij'} \quad \forall j \neq j', \quad j, j' \in C_{i})
$$

- The consumer's unconditional choice probability is given by:

$$
P_{ij \mid \alpha, \epsilon} = P_{i \Upsilon \mid \alpha, \epsilon} P_{ij \mid \Upsilon \alpha \epsilon}
$$

- Parameters are estimated by maximizing the joint likelihood of consideration and purchase given by:

$$
L = \prod_{i = 1}^{N} \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} \left( \prod_{l = 1}^{L} \prod_{j = 1}^{J} P_{i \Upsilon \mid \alpha, \epsilon}^{\vartheta_{il}} P_{ij \mid \Upsilon \alpha \epsilon}^{\delta_{ij}}\right) f(\alpha)f(\epsilon) d\alpha d\epsilon
$$

- Since this would result in lumpy probabilities which cannot be optimized using common optimization routines, a karnel-smoothed frequency simulator is used in the estimation and smooth the probabilities using a multivariate scaled logistic CDF:

$$
F(\omega_{1}, ..., \omega_{T}; s_{1}, ..., s_{T}) = \frac{1}{1 + \sum_{t = 1}^{T} \exp(-s_{t}\omega_{t})} \quad \forall t = 1, ..., T
$$
where $s_{1}, ..., s_{T}$ are scaling parameters.


### Estimation of Consumer Price Beliefs

- Assume that consumers have rational expectations about prices and know the company-specific distributions of prices
- To reflect consumer's knowledge of the prices present in the market before the search, I only use the prices charged by the previous insurers of consumers in the sample
- Assume prices have an EV Type I distribution and regress all prices charged by previous insurers on personal and policy characteristics as well as company-specific fixed effects:

$$
p_{ij} \sim EV(\eta_{ij}; \mu) \quad \text{with} \quad \eta_{ij} = D_{ij}\zeta
$$
where $\zeta$ is a coefficient vector and $D_{ij}$ contatins the personal and polcy characteristics and company-specific fixed effects

### Estimation Procedure

1. Estimate price beliefs
1. Estimate the search and choice model
    1. Take $Q$ draws for $\alpha_{ij}$ and $\epsilon_{ij}$ for each consumer / company combination
    1. Calculate $w_{t}^{q}$ for the consideration set and conditional purchase probabilities
    1. Calculate the smoothed consideration and purchase probabilities
    1. Average the unconditional purchase probabilities across all $Q$ draws for $\alpha_{ij}$ and $\epsilon_{ij}$

